name: fake_settings
description: "Samsung stili sahte ayarlar uygulaması. 30+ kategori, sahte Telefon Hakkında sayfası ve sistem ayarlarına yönlendirme içerir."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔹 Sistem ayarlarını açmak için
  url_launcher: ^6.3.1
  android_intent_plus: ^4.0.3

  # 🔹 Samsung benzeri ikonlar
  font_awesome_flutter: ^10.7.0

  # 🔹 Durum kaydı için
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
