name: samsung_settings_clone
description: Sahte Samsung OneUI8 Ayarlar uygulaması (Android 16 görünümlü)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
